name: Build Next.js and update to Walrus

on:
  push:
    branches:
      - "master"
    paths:
      - "src/**"
      - "public/**"
      - "package.json"
      - "vite.config.ts"
      - ".github/workflows/publish.yaml"
      - ".github/actions/build/action.yaml"
  workflow_dispatch:
    inputs:
      update-walrus-site:
        description: "Update the Walrus Site"
        type: boolean
        required: true
        default: false

concurrency: ci-${{ github.ref }}

permissions:
  contents: read

jobs:
  publish-walrus:
    name: Update Walrus Site
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || inputs.update-walrus-site == true }}
    env:
      NO_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build

      - name: Download Walrus Sites config
        run: |
          mkdir -p walrus-config
          curl -o walrus-config/config.yaml https://raw.githubusercontent.com/MystenLabs/walrus-sites/main/site-builder/assets/builder-example.yaml
        shell: bash

      - name: Deploy site to Walrus
        uses: zktx-io/walrus-ga@v0.1.1
        with:
          config-path: 'walrus-config/config.yaml'
          site-path: 'dist'
          network: 'testnet'
          object-id: ${{ vars.WALRUS_SITE_OBJECT }}
        env:
          SUI_ADDRESS: ${{ vars.SUI_ADDRESS }}
          SUI_KEYSTORE: ${{ secrets.SUI_KEYSTORE }}
